version: '2'
services:
  device:
    image: iiot-book-2/aws-iot-device-sdk-python-v2
    build: 
        context: ./connect_device_package
        args:
          - AWS_DEVICE_NAME=device2
          - AWS_IOT_ENDPOINT=a29ou9oy5zw49b-ats.iot.us-east-1.amazonaws.com
          - AWS_DEVICE_TOPIC=/devices/device1/sensors
    volumes:
        - ./connect_device_package/aws-iot-device-sdk-python-v2/samples:/samples
        - ./certificates:/certificates
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks: 
      - iiot-book-2-net-edge
    depends_on:
      - opc-ua-server
  opc-ua-server:
    build: ./node-opcua-sampleserver
    ports:
      - "26543:26543"
    networks: 
      - iiot-book-2-net-edge
networks:
  iiot-book-2-net-edge: 