version: "3"
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.4.31-community
    ports:
      - "7474:7474"
      - "7687:7687"
    networks: 
    - iiot-book-2-net
    environment:
    - NEO4J_AUTH=neo4j/admin
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    - NEO4J_EDITION=docker_compose
 
networks:
    iiot-book-2-net: 
      external: true