version: '2'
services:
  jupyter-ds:
    image: jupyter/datascience-notebook
    volumes:
    - ./work:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token=''"
    ports:
      - "8888:8888"
    networks: 
      - iiot-book-2-net
networks:
  iiot-book-2-net: 