version: '2'
services:
  python-device:
    image: iiot-book-2/python-device
    build: ./python-device
    tty: True
    environment:
        - IOTHUB_DEVICE_CONNECTION_STRING=HostName=iiot-book-2-hub.azure-devices.net;DeviceId=device1;SharedAccessKey=OCSXWb3M+UmKf1Kw5ywhpy+MRmsTc7WDRAIoTIPm7kw=
    networks: 
      - iiot-book-2-net-edge
  opc-ua-server:
    build: ./node-opcua-sampleserver
    ports:
      - "26543:26543"
    networks: 
      - iiot-book-2-net-edge
networks:
  iiot-book-2-net-edge: 